var content = '[' +
    '{"page_num":1, "page_title":"", "content_type":"content_without_image", "text":"<br>It was a dark and stormy night. Our family was just sitting down for dinner when we started hearing strange noises coming from the attic. Suddenly a light turned on in the kitchen and the TV started blaring from the living room. Energy monsters were attacking our house, and they were hungry for energy! <br><br>The monsters started out too weak to do much damage, but they quickly grew stronger as they feasted on wasted electricity. Help stop the monsters before it\'s too late...", "img_data":""},' +
    '{"page_num":2, "page_title":"Contents", "content_type":"content_without_image", "text":"<ul><li>15 room tiles</li><li>36 monster cards</li><li>36 human cards</li><li>3 human tokens </li><li>3 monster tokens ( Wattwolf, Ampire, and Bonehead)</li><li>1 energy spinner</li><li>Hit point tokens (green marbles)</li></ul>", "img_data":""},' +
    '{"page_num":3, "page_title":"Board Setup", "content_type":"content_with_image", "text":"Build a house by arranging the 15 room tiles so that all rooms are connected by doorways. Place rooms with the dark side of the tile facing up. The layout of the rooms does not need to make sense--remember this is a haunted house!<br><br>There are three special rooms, the Attic, the Basement, and the Back Porch. Monsters start in these rooms, so it\'s a good idea to make sure they\'re not too close to the Dining Room.", "img_data":"img/board_tiles.png"},' +
    '{"page_num":4, "page_title":"Team Setup", "content_type":"content_without_image", "text":"<ol><li>Players form two teams: humans versus monsters.</li><li>Shuffle the monster deck and deal 5 cards to the monster team.</li><li>Shuffle the human deck and deal 5 cards to the human team. </li><li>Place the 3 human tokens in the dining room for dinner.</li><li>Place 1 monster token in each of the three portal rooms: the Attic, the Basement, and the Back Porch. </li><li>Set the spinner to 100  Watts. This is the minimum amount used by things that are always on in your house (like the water heater and refrigerator).</li><li>Give each team 6 hit points (green marbles).</li></ol>", "img_data":""},{"page_num":5, ' +
    '"page_title":"Basic Gameplay", "content_type":"content_without_image", "text":"<br>Monsters go first and then the two teams alternate turns. On your turn, your team can do the following three actions in order:<br><ol><li>Draw new cards to bring your hand up to 5 cards.</li><li>Move one of your tokens at most 1 space through an open door to an adjacent room.</li><li>Play as many cards as you want from your hand, but with at most one attack card. You may also discard up to one card.</li></ol><h2>Objective</h2>Play ends when one of the teams loses all of their points.", "img_data":"img_data"},{"page_num":6, ' +
    '"page_title":"energy Spinner", "content_type":"content_with_image", "text":"The energy spinner shows how much energy is being used and how strong the monsters are.<br><br>Use the spinner when playing an attack card.<br><br>Set the arrow to match the total energy used by all rooms in the house. The maximum value is 1,400  Watts, even if the total energy of all rooms in the house is more than that.<br><br>The human team wants the spinner to land in the black area, and the monster team wants it to land in the color area.", "img_data":"img/spinner.png"},' +
    '{"page_num":7, "page_title":"Playing Waste Cards", "content_type":"content_with_image", "text":"Monsters gain strength by wasting energy.<br>The monster team plays waste cards to turn on appliances and devices. Before playing a waste card, you must move the correct monster to the room shown on the card.<br><br>For example, to turn on the TV, you must first move the Ampire to the living room. After playing the card, flip the room tile over to the light side and add 200  Watts to the energy spinner.<br><h3>NOTE: </h3>If there is a human in the same room, then the room is guarded. You cannot play a waste card in a guarded room.<br>", "img_data":"img/monster_card.png"},' +
    '{"page_num":8, "page_title":"Playing Switch Cards", "content_type":"content_with_image", "text":"Humans can turn things off by playing one of three switch cards (light switches, energy buttons, and sockets). Room tiles show the type of switch that can be used in that room.<br><br>To turn something off, move a human to the room and play the matching switch card. Flip the room tile back over to the dark side and reduce the energy spinner by the indicated amount.<br><h3>NOTE: </h3>If there is a monster in the room, then the room is guarded. You cannot play a switch card in a guarded room.", "img_data":"img/switch_card.png"},' +
    '{"page_num":9, "page_title":"Playing Attack Cards", "content_type":"content_with_image", "text":"Attack cards are played against an opponent in the same room as one of your tokens.<br><br>Spin the spinner. If it lands in the colored area for monsters or in the black area for humans, your opponent loses one hit point.<br><br>If the spinner lands on the opposite color, nothing happens.<br><br>When you lose all 6 of your hit points, you lose the game.<br><br>Attack cards can also be used to break down locked doors in the same room. Spin the spinner. If you\'re successful, the lock is broken.", "img_data":"img/attack_card.png"},' +
    '{"page_num":10, "page_title":"Locking a door", "content_type":"content_with_image", "text":"Play a Skeleton Key card to lock doors. Place a marker on a doorway in a room occupied by one of your team\'s tokens.<br><br>After the door is locked, it can only be opened again by playing an Attack Card. Both the humans and the monsters can attack a door to break it down.", "img_data":"img/skeleton_key.png"},' +
    '{"page_num":11, "page_title":"About the Monsters", "content_type":"content_with_image", "text":"Bonehead is a mindless energy waster. He\'s always forgetting to turn things off when they\'re not being used. ", "img_data":"img/bonehead.png"},' +
    '{"page_num":12, "page_title":"About the Monsters", "content_type":"content_with_image", "text":"Ampires love doing things inefficiently. Watch out or they\'ll run the dishwasher when it\'s half empty.", "img_data":"img/ampire.png"},' +
    '{"page_num":13, "page_title":"About the Monsters", "content_type":"content_with_image", "text":" Wattwolf wastes energy by using old, inefficient appliances.", "img_data":"img/ Wattwolf.png"}]';

var appliance_list = '[' +
    '{"appliance_num":1, "appliance_name":"washing machine", "appliance_icon":"img/appliances/washer.png", "energy":500, "long_description":"A typical washing has an energy consumption of <b>500 Watt</b> & used approximately 4 hours per week on average by a family in North America." },' +
    '{"appliance_num":2, "appliance_name":"fridge", "appliance_icon":"img/appliances/refrigerator.png", "energy":1200, "long_description":"A typical refrigerator has an energy consumption of <b>1200 Watt</b> & used approximately 24 X 7 on average by a family in North America."  },' +
    '{"appliance_num":3, "appliance_name":"microwave", "appliance_icon":"img/appliances/microwave.png", "energy":1000, "long_description":"A typical microwave has an energy consumption of <b>1000 Watt</b> & used approximately 4 hours per week on average by a family in North America." },' +
    '{"appliance_num":4, "appliance_name":"kitchen chimney", "appliance_icon":"img/appliances/chimney.png", "energy":250, "long_description":"A typical kitchen chimney has an energy consumption of <b>250 Watt</b> & used approximately 8 hours per week on average by a family in North America." },' +
    '{"appliance_num":5, "appliance_name":"toaster", "appliance_icon":"img/appliances/toaster.png", "energy":1100, "long_description":"A typical toaster has an energy consumption of <b>1100 Watt</b> & used approximately 2 hours per week on average by a family in North America." },' +
    '{"appliance_num":6, "appliance_name":"hair dryer", "appliance_icon":"img/appliances/hair_dryer.png", "energy":1500, "long_description":"A typical hair dryer has an energy consumption of <b>1500 Watt</b> & used approximately half and hour per week on average by a family in North America." },' +
    '{"appliance_num":7, "appliance_name":"iron", "appliance_icon":"img/appliances/iron.png", "energy":1100, "long_description":"A typical iron has an energy consumption of <b>1100 Watt</b> & used approximately half an hour per week on average by a family in North America." },' +
    '{"appliance_num":8, "appliance_name":"router", "appliance_icon":"img/appliances/router.png", "energy":6, "long_description":"A typical washing has an energy consumption of <b>6 Watt</b> & used approximately 24 X 7 on average by a family in North America." },' +
    '{"appliance_num":9, "appliance_name":"television", "appliance_icon":"img/appliances/television.png", "energy":85, "long_description":"A typical LCD television has an energy consumption of <b>85 Watt</b> & used approximately 24 X 7 on average by a family in North America."},' +
    '{"appliance_num":10, "appliance_name":"space heater", "appliance_icon":"img/appliances/space_heater.png", "energy":1100, "long_description":"A typical space heater has an energy consumption of <b>1100 Watt</b> & used in the winter approximately 24 X 7 on average by a family in North America."},' +
    '{"appliance_num":11, "appliance_name":"lamp", "appliance_icon":"img/appliances/lamp.png", "energy":40, "long_description":"A typical lamp has an energy consumption of <b>1100 Watt</b> & used approximately 20 hours a week on average by a family in North America." },' +
    '{"appliance_num":12, "appliance_name":"laptop", "appliance_icon":"img/appliances/laptop.png", "energy":60, "long_description":"A typical laptop has an energy consumption of <b>60 Watt</b> & used approximately 18 hours a week on average by a family in North America."},' +
    '{"appliance_num":13, "appliance_name":"charger", "appliance_icon":"img/appliances/charger.png", "energy":4, "long_description":"A typical charger has an energy consumption of <b>4 Watt</b> & used approximately 12 hours per week on average by a family in North America."}]';